style: prettier files (#16)
* style: prettier files

* docs: fix typo mistakes

---------

Co-authored-by: Roee Shachar <shacharroy142gmail.com>

diff --git a/.github/workflows/update-artifacts-file.yaml b/.github/workflows/update-artifacts-file.yaml
--- a/.github/workflows/update-artifacts-file.yaml
+++ b/.github/workflows/update-artifacts-file.yaml
@@ -4,21 +4,21 @@ on:
   workflow_call:
     inputs:
       scope:
-        description: 'Scope of artifacts.json file to update'
+        description: "Scope of artifacts.json file to update"
         type: string
         required: false
-        default: ''
+        default: ""
       type:
-        description: 'Artifact`s type'
+        description: "Artifact`s type"
         type: string
         required: false
-        default: 'docker'
+        default: "docker"
       artifact-name:
-        description: 'Artifact`s name'
+        description: "Artifact`s name"
         type: string
         required: true
       artifact-tag:
-        description: 'Aritfact`s tag'
+        description: "Artifact`s tag"
         type: string
         required: true
 
@@ -27,66 +27,63 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout helm-charts repository
+        uses: actions/checkout@v3
+        with:
+          repository: MapColonies/helm-charts
+          path: helm-charts
+          token: ${{ secrets.GH_PAT }}
 
-    - name: Checkout helm-charts repository
-      uses: actions/checkout@v3
-      with:
-        repository: MapColonies/helm-charts
-        path: helm-charts
-        token: ${{ secrets.GH_PAT }}
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "18"
 
-    - name: Set up Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '18'
+      - name: Modify artifacts.json
+        run: |
+          cd helm-charts/${{ inputs.scope }}
+          node -e "
+          const fs = require('fs');
+          const path = './artifacts.json';
+          let data = {};
+          // Check if 'artifacts.json' file already exists
+          if (fs.existsSync(path)) {
+            data = JSON.parse(fs.readFileSync(path, 'utf8'));
+          }
+          // Ensure nested structure: docker -> registry -> artifact:tag
+          if (!data['${{ inputs.type }}']) data['${{ inputs.type }}'] = {};
+          if (!data['${{ inputs.type }}']['${{ secrets.ACR_URL }}']) data['${{ inputs.type }}']['${{ secrets.ACR_URL }}'] = {};
+          data['${{ inputs.type }}']['${{ secrets.ACR_URL }}']['${{ inputs.artifact-name }}'] = '${{ inputs.artifact-tag }}';
+          // Writing new file contents
+          fs.writeFileSync(path, JSON.stringify(data, null, 2));
+          "
 
-    - name: Modify artifacts.json
-      run: |
-        cd helm-charts/${{ inputs.scope }}
-        node -e "
-        const fs = require('fs');
-        const path = './artifacts.json';
-        let data = {};
-        // Check if 'artifacts.json' file already exists
-        if (fs.existsSync(path)) {
-          data = JSON.parse(fs.readFileSync(path, 'utf8'));
-        }
-        // Ensure nested structure: docker -> registry -> artifact:tag
-        if (!data['${{ inputs.type }}']) data['${{ inputs.type }}'] = {};
-        if (!data['${{ inputs.type }}']['${{ secrets.ACR_URL }}']) data['${{ inputs.type }}']['${{ secrets.ACR_URL }}'] = {};
-        data['${{ inputs.type }}']['${{ secrets.ACR_URL }}']['${{ inputs.artifact-name }}'] = '${{ inputs.artifact-tag }}';
-        // Writing new file contents
-        fs.writeFileSync(path, JSON.stringify(data, null, 2));
-        "
+      - name: Commit changes
+        run: |
+          cd helm-charts
+          git config --global user.name "mapcolonies[bot]"
+          git config --global user.email "devops[bot]@mapcolonies.com"
 
-    - name: Commit changes
-      run: |
-        cd helm-charts
-        git config --global user.name "mapcolonies[bot]"
-        git config --global user.email "devops[bot]@mapcolonies.com"
+          git add .
+          # Add "|| true" for not failing on this line
+          git commit -m "Update artifacts.json for ${{ inputs.scope }}" -m "with ${{ inputs.type }} artifact: ${{ inputs.artifact-name }}:${{ inputs.artifact-tag }}" || true
 
-        git add .
-        # Add "|| true" for not failing on this line
-        git commit -m "Update artifacts.json for ${{ inputs.scope }}" -m "with ${{ inputs.type }} artifact: ${{ inputs.artifact-name }}:${{ inputs.artifact-tag }}" || true
+          success=false
+          for ((i=1; i<=5; i++)); do
+            echo "Attempt number $i"
+            if git push; then
+              success=true
+              break
+            else
+              sleep 5
+              # --ff for fast-forward
+              git pull origin master --ff
+            fi
+          done
 
-        success=false
-        for ((i=1; i<=5; i++)); do
-          echo "Attempt number $i"
-          if git push; then
-            success=true
-            break
-          else
-            sleep 5
-            # --ff for fast-forward
-            git pull origin master --ff
+          if [ "$success" = false ]; then
+            echo "Failed to push changes."
+            exit 1
           fi
-        done
-
-        if [ "$success" = false ]; then
-          echo "Failed to push changes."
-          exit 1
-        fi
-      env:
-        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
