feat: retry mechanism for updating artifacts file (#13)
* feat: add retries for git push

* chore: add comment

* chore: add comment

* chore: retry

* feat: add retries for git push

* chore: cosmetics

* chore: enter in eof

* chore: revert to master

* chore: change echo

---------

Co-authored-by: Roee Shachar <shacharroy142gmail.com>

diff --git a/.github/workflows/update-artifacts-file.yaml b/.github/workflows/update-artifacts-file.yaml
--- a/.github/workflows/update-artifacts-file.yaml
+++ b/.github/workflows/update-artifacts-file.yaml
@@ -66,8 +66,27 @@ jobs:
         cd helm-charts
         git config --global user.name "mapcolonies[bot]"
         git config --global user.email "devops[bot]@mapcolonies.com"
+
         git add .
-        git commit -m "Update artifacts.json"
-        git push
+        # Add "|| true" for not failing on this line
+        git commit -m "Update artifacts.json" || true
+
+        success=false
+        for ((i=1; i<=5; i++)); do
+          echo "Attempt number $i"
+          if git push; then
+            success=true
+            break
+          else
+            sleep 5
+            # --ff for fast-forward
+            git pull origin master --ff
+          fi
+        done
+
+        if [ "$success" = false ]; then
+          echo "Failed to push changes."
+          exit 1
+        fi
       env:
         GITHUB_TOKEN: ${{ secrets.GH_PAT }}
